name: "XNET: Stale Guard"
on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          stale-issue-message: "This issue is inactive. Closing for efficiency. 💎 XNET"
          days-before-stale: 30
          days-before-close: 7