#
# An auto defined `clippy` feature was introduced,
# but it was found to clash with user defined features,
# so was renamed to `cargo-clippy`.
#
# If you want standard clippy run:
# RUSTFLAGS= cargo clippy
[target.'cfg(feature = "cargo-clippy")']
rustflags = [
  "-Dclippy::all",
  "-Dclippy::correctness",
  "-Dclippy::perf",
  "-Dclippy::unwrap_used",
  "-Dclippy::expect_used",
  "-Dclippy::panic",
  "-Dclippy::todo",
  "-Dclippy::unimplemented",
  "-Dclippy::large_futures",
  "-Aclippy::type_complexity",     
  "-Aclippy::too_many_arguments",       
  "-Aclippy::large_enum_variant",     
  "-Aclippy::unnecessary_cast",         
  "-Aclippy::identity-op",              
  "-Aclippy::erasing_op",              
  "-Aclippy::eq_op",                   
]