name: "XNET: DevAlert Notification"

on:
  pull_request:
    types: [labeled]

jobs:
  notify-xnet-team:
    runs-on: ubuntu-latest
    if: startsWith(github.event.label.name, 'A1-')
    steps:
      - name: Send Notification to Telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          format: markdown
          message: |
            **XNET Protocol - Pull Request Update**

            The label *${{ github.event.label.name }}* was applied.
            
             **Title:** ${{ github.event.pull_request.title }}
             **PR Link:** [Check Pull Request](${{ github.event.pull_request.html_url }})
            
            Action required by Dev Team.