name: "XNET: Label Audit"
on:
  pull_request:
    types: [labeled, opened, synchronize, unlabeled]

jobs:
  check-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Check for Required Labels
        uses: mheap/github-action-required-labels@v5
        with:
          mode: minimum
          count: 1
          labels: "status:core-approved, status:needs-audit, enhancement"