name: "XNET: Quality Label Audit"

on:
  pull_request:
    types: [labeled, opened, synchronize, unlabeled]
    paths:
      - 'runtime/**'
      - 'node/**'
      - 'pallets/**'

jobs:
  check-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Verify Mandatory Labels
        uses: mheap/github-action-required-labels@v5
        with:
          mode: minimum
          count: 1
          labels: "status:needs-audit, status:community-review, status:core-approved"