name: "XNET CI: Monthly Release Snapshot"

on:
  schedule:
    - cron: "0 0 1 * *"

jobs:
  snapshot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Archive XNET Protocol Repository"
        uses: softprops/action-gh-release@v1
        with:
          tag_name: monthly-${{ github.sha }}
          name: "XNET Protocol Source Archive: $(date +'%Y-%m')"
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}